SaiBabaHospital/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SaiBabaHospital.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


        public ActionResult Doctors()
        {
            return View();
        }

        public ActionResult Department()
        {
            return View();
        }

        public ActionResult Accommodation()
        {
            return View();
        }
        public ActionResult Career()
        {
            return View();
        }
        public ActionResult TPA()
        {
            return View();
        }

        public ActionResult Social()
        {
            return View();
        }

        public ActionResult Homemain()
        {
            return View();
        }

        public ActionResult ComingSoon()
        {
            return View();
        }

        public ActionResult Blog()
        {
            return View();
        }

    }
}

SaiBabaHospital/Controllers/HomeEyeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SaiBabaHospital.Controllers
{
    public class HomeEyeController : Controller
    {
        //
        // GET: /HomeEye/
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Doctors()
        {
            return View();
        }

        public ActionResult AboutUsRaipur()
        {
            return View();
        }

        public ActionResult Services()
        {
            return View();
        }

        public ActionResult Event()
        {
            return View();
        }

        public ActionResult Media()
        {
            return View();
        }

        public ActionResult Career()
        {
            return View();
        }

        public ActionResult ContactUs()
        {
            return View();
        }

        public ActionResult Blog()
        {
            return View();
        }

        public ActionResult Appointment()
        {
            return View();
        }

	}
}

SaiBabaHospital/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<section class="inner-bg over-layer-black" style="background-image: url('../HospitalDemoSimple/img/bg/4.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="mini-title inner-style-2">
                    <h3>About Us</h3>

                </div>
            </div>
        </div>
    </div>
</section>


<section class="about animatedParent animateOnce">
    <div class="container">
        <div class="section-title">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="text-center">
                        <h2>Welcome To <span class="color-defult">Sai Baba Hospital</span></h2>
                        <div class="line-border-center bg-defult"></div>
                        <p style="text-align:justify">
                            Sai Baba Nursing Home was started in the year 2003. It has now become a leading private Hospital of Chhattisgarh.
                            Sai Baba Nursing Home is providing the complete care for the Women. Giving standard treatment as well as advanced medical and
                            surgical treatment and high-tech equipment with back-up round the clock Doctors, qualified work force and proficient consultants.
                            We believe in providing best care in most affordable price.
                            <br /><br />
                            We are providing the complete care before, during and after pregnancy and also dealing with high risk pregnancies such as Diabetes mellitus,
                            Hypertension, Heart Disease, recurrent pregnancy loss, Intrauterine growth retardation etc. through the pregnancy and labour.
                            We are using labour analgesia, NST and Partogram for each and every patient. Our hospital also facilitates painless labour.
                            <br /><br />
                            We provide specialist medical as well as surgical management of all types of gynaecological problem i.e menstrual abnormalities , Prolapse,
                            fibroid and other tumors of uterus and ovary, pelvic inflammatory disease , tubal recanalisation by micro surgery.
                            <br /><br />
                            Ectopic prenancy, Ovarian cyst and tomies can be performed laproscopically with the least pain to your early return to your daily activities.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="section-content">
            <div class="row">
                <div class="about-feature">
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                        <div class="appointment-item style-gray animated fadeInLeftShort slow delay-250">
                            <i class="flaticon-ribbon"></i>
                            <h5><a href="#">Our Doctors</a></h5>
                            <div class="line-border-center bg-gray"></div>
                            <p>Choose by name, specialty, city and more.</p>
                            <button class="btn btn-theme btn-sm">Book Now</button>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                        <div class="appointment-item style-gray animated fadeInLeftShort slow delay-500">
                            <i class="flaticon-cardiogram"></i>
                            <h5><a href="#">Health Check</a></h5>
                            <div class="line-border-center bg-gray"></div>
                            <p>Find maps and more for all locations.</p>
                            <button class="btn btn-theme btn-sm">Check Now</button>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 center-block">
                        <div class="appointment-item style-gray animated fadeInLeftShort slow delay-750">
                            <i class="flaticon-first-aid-kit"></i>
                            <h5><a href="#">Appointments</a></h5>
                            <div class="line-border-center bg-gray"></div>
                            <p>Click in, walk in or call us today.</p>
                            <button class="btn btn-theme btn-sm">Book Now</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

SaiBabaHospital/Views/Home/Accommodation.cshtml
@{
    ViewBag.Title = "Accommodation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<img src="~/HospitalDemoSimple/aboutbanner.jpg" />

SaiBabaHospital/Views/Home/Blog.cshtml
@{
    ViewBag.Title = "Blog";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="inner-bg over-layer-black" style="background-image: url('../HospitalDemoSimple/img/bg/4.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="mini-title inner-style-2">
                    <h3>Blog</h3>
                    <p><a href="index-one.html">Home</a> <span class="fa fa-angle-right"></span> <a href="#">Blog</a></p>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="blog-area bg-f8 animatedParent animateOnce">
    <div class="container">
        <div class="section-content">
            <div class="row">
                <div class="blog-feature">
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <div class="blog-item style-1">
                            <div class="blog-date text-center">
                                <i class="pe-7s-link"></i>
                            </div>
                            <div class="blog-img">
                                <a href="#"><img src="~/HospitalDemoSimple/img/blog/1.jpg" alt=""></a>
                                <div class="blog-event-date">
                                    <h3>13 <small>Jun</small></h3>
                                </div>
                            </div>
                            <div class="blog-content">
                                <a href="#"><h4>What's the Right Choice? </h4></a>
                                <i class="fa fa-user-o"></i> <a href="#">Admin</a> | <i class="fa fa-heart-o"></i> <a href="#">Like :20 </a> | <i class="fa fa-comment-o"></i><a href="#"> Comments: 10</a>
                                <p>come from a family of doctors and I was suffering from morbid obesity with co-morbidities like diabetes, hypertension, and sleep apnoea.</p>
                                <a href="#" class="btn btn-simple">Read More</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <div class="blog-item style-1">
                            <div class="blog-date text-center">
                                <i class="pe-7s-link"></i>
                            </div>
                            <div class="blog-img">
                                <a href="#"><img src="~/HospitalDemoSimple/img/blog/2.jpg" alt=""></a>
                                <div class="blog-event-date">
                                    <h3>17 <small>Jun</small></h3>
                                </div>
                            </div>
                            <div class="blog-content">
                                <a href="#"><h4>Caregiver Series </h4></a>
                                <i class="fa fa-user-o"></i> <a href="#">Admin</a> | <i class="fa fa-heart-o"></i> <a href="#">Like :20 </a> | <i class="fa fa-comment-o"></i><a href="#"> Comments: 10</a>
                                <p>come from a family of doctors and I was suffering from morbid obesity with co-morbidities like diabetes, hypertension, and sleep apnoea.</p>
                                <a href="#" class="btn btn-simple">Read More</a>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 col-sm-6 col-xs-12 center-block">
                        <div class="blog-item style-1">
                            <div class="blog-date text-center">
                                <i class="pe-7s-link"></i>
                            </div>
                            <div class="blog-img">
                                <a href="#"><img src="~/HospitalDemoSimple/img/blog/3.jpg" alt=""></a>
                                <div class="blog-event-date">
                                    <h3>19 <small>Jun</small></h3>
                                </div>
                            </div>
                            <div class="blog-content">
                                <a href="#"><h4>Little Hats, Big Hearts </h4></a>
                                <i class="fa fa-user-o"></i> <a href="#">Admin</a> | <i class="fa fa-heart-o"></i> <a href="#">Like :20 </a> | <i class="fa fa-comment-o"></i><a href="#"> Comments: 10</a>
                                <p>come from a family of doctors and I was suffering from morbid obesity with co-morbidities like diabetes, hypertension, and sleep apnoea.</p>
                                <a href="#" class="btn btn-simple">Read More</a>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <div class="blog-item style-1">
                            <div class="blog-date text-center">
                                <i class="pe-7s-link"></i>
                            </div>
                            <div class="blog-img">
                                <a href="#"><img src="~/HospitalDemoSimple/img/blog/4.jpg" alt=""></a>
                                <div class="blog-event-date">
                                    <h3>13 <small>Jun</small></h3>
                                </div>
                            </div>
                            <div class="blog-content">
                                <a href="#"><h4>What's the Right Choice? </h4></a>
                                <i class="fa fa-user-o"></i> <a href="#">Admin</a> | <i class="fa fa-heart-o"></i> <a href="#">Like :20 </a> | <i class="fa fa-comment-o"></i><a href="#"> Comments: 10</a>
                                <p>come from a family of doctors and I was suffering from morbid obesity with co-morbidities like diabetes, hypertension, and sleep apnoea.</p>
                                <a href="#" class="btn btn-simple">Read More</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <div class="blog-item style-1">
                            <div class="blog-date text-center">
                                <i class="pe-7s-link"></i>
                            </div>
                            <div class="blog-img">
                                <a href="#"><img src="~/HospitalDemoSimple/img/blog/5.jpg" alt=""></a>
                                <div class="blog-event-date">
                                    <h3>17 <small>Jun</small></h3>
                                </div>
                            </div>
                            <div class="blog-content">
                                <a href="#"><h4>Caregiver Series </h4></a>
                                <i class="fa fa-user-o"></i> <a href="#">Admin</a> | <i class="fa fa-heart-o"></i> <a href="#">Like :20 </a> | <i class="fa fa-comment-o"></i><a href="#"> Comments: 10</a>
                                <p>come from a family of doctors and I was suffering from morbid obesity with co-morbidities like diabetes, hypertension, and sleep apnoea.</p>
                                <a href="#" class="btn btn-simple">Read More</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-6 col-xs-12 center-block">
                        <div class="blog-item style-1">
                            <div class="blog-date text-center">
                                <i class="pe-7s-link"></i>
                            </div>
                            <div class="blog-img">
                                <a href="#"><img src="~/HospitalDemoSimple/img/blog/6.jpg" alt=""></a>
                                <div class="blog-event-date">
                                    <h3>19 <small>Jun</small></h3>
                                </div>
                            </div>
                            <div class="blog-content">
                                <a href="#"><h4>Little Hats, Big Hearts </h4></a>
                                <i class="fa fa-user-o"></i> <a href="#">Admin</a> | <i class="fa fa-heart-o"></i> <a href="#">Like :20 </a> | <i class="fa fa-comment-o"></i><a href="#"> Comments: 10</a>
                                <p>come from a family of doctors and I was suffering from morbid obesity with co-morbidities like diabetes, hypertension, and sleep apnoea.</p>
                                <a href="#" class="btn btn-simple">Read More</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



<!-- divider start -->
<section class="service-area over-layer-default" style="background-image: url(../HospitalDemoSimpleimg/img/bg/5.jpg);">
    <div class="container padding-bottom-none padding-top-40">
        <div class="section-content">
            <div class="row">
                <div class="col-sm-12 col-md-4">
                    <div class="service-item style-1 text-white border-right">
                        <div class="service-icon">
                            <i class="pe-7s-call"></i>
                        </div>
                        <div class="content">
                            <h5><a href="#">Give us a Call</a></h5>
                            <p>+91-0771-4037979</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-4">
                    <div class="service-item style-1 text-white border-right">
                        <div class="">
                            <i class="pe-7s-mail-open"></i>
                        </div>
                        <div class="content">
                            <h5><a href="#">Send us a Message</a></h5>
                            <p>operation.eye@sbhhospital.com</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-4">
                    <div class="service-item style-1 text-white">
                        <div class="">
                            <i class="pe-7s-map-marker"></i>
                        </div>
                        <div class="content">
                            <h5><a href="#">Visit our Location</a></h5>
                            <p>
                                Near Fafadih Choti Line,
                                Raipur
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- divider end -->

SaiBabaHospital/Views/Home/Career.cshtml
@{
    ViewBag.Title = "Career";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<img src="~/HospitalDemoSimple/aboutbanner.jpg" />

SaiBabaHospital/Views/Home/ComingSoon.cshtml
@{
    ViewBag.Title = "ComingSoon";
    Layout = null;
    <title> Sai Baba Hospital, Raipur</title>
}
<link rel="shortcut icon" type="image/x-icon" href="~/HospitalDemoEye/logoEYEfavicon.png">
<link href="~/HospitalDemoSimple/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/HospitalDemoSimple/css/style.css" rel="stylesheet" />
<link href="~/HospitalDemoSimple/css/responsive.css" rel="stylesheet" />

<section class="over-layer-black error" style="background-image: url('../HospitalDemoSimple/img/bg/1.jpg')">
    <div class="container">
        <div class="section-content">
            <div class="row">
                <div class="col-md-12">
                    <div class="content text-center">
                        <h2 class="color-white" style="font-size:125px;">Coming<span>Soon</span></h2>
                        <p class="color-white">Sorry, the page you were looking is under process!</p>
                        <a href="@Url.Action("Homemain","Home")" class="btn btn-theme btn-contact hvr-grow-shadow"> Go to Main pages</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<a href="#" class="scrollup"><i class="pe-7s-up-arrow" aria-hidden="true"></i></a>
<script src="~/HospitalDemoSimple/js/jquery.min.js"></script>
<script src="~/HospitalDemoSimple/js/bootstrap.min.js"></script>
<script src="~/HospitalDemoSimple/js/bootstrap-datepicker.min.js"></script>
<script src="~/HospitalDemoSimple/js/css3-animate-it.js"></script>
<script src="~/HospitalDemoSimple/js/bootstrap-dropdownhover.min.js"></script>
<script src="~/HospitalDemoSimple/js/owl.carousel.min.js"></script>
<script src="~/HospitalDemoSimple/js/gallery.js"></script>
<script src="~/HospitalDemoSimple/js/player.min.js"></script>
<script src="~/HospitalDemoSimple/js/retina.js"></script>
<script src="~/HospitalDemoSimple/js/comming-soon.js"></script>
<script src="~/HospitalDemoSimple/js/script.js"></script>

SaiBabaHospital/Views/Home/Homemain.cshtml
@{
    ViewBag.Title = "Homemain";
    Layout = "";
    <title> Sai Baba Hospital, Raipur</title>
}
<link rel="shortcut icon" type="image/x-icon" href="~/HospitalDemoEye/logoEYEfavicon.png">
<link href="~/MainHomePageDesign/css/style.css" rel="stylesheet" />
<link href="~/MainHomePageDesign/css/css_slider.css" rel="stylesheet" />
<link href="~/MainHomePageDesign/css/bootstrap.css" rel="stylesheet" />
<link href="~/MainHomePageDesign/css/font-awesome.min.css" rel="stylesheet" />



<header class="py-3">
    <div class="container">
        <div id="logo">
            <div class="row">
                <div class="col-md-4">
                    <img src="~/HospitalDemoSimple/logo.png" height="80" />
                </div>
                <div class="col-md-8">
                    <center>
                        <span style="font-weight:bold;font-size:28px;color:white">
                            Welcome to SBH Group of Hospitals.
                            Where would you like to go?
                        </span>
                    </center>


                </div>
            </div>


            @*<h1> <a href="index.html"><span class="fa fa-stethoscope" aria-hidden="true"></span> Dental Health</a></h1>*@

        </div>
        <!-- nav -->

        <div class="clear"></div>
        <!-- //nav -->
    </div>
</header>


<div class="banner" id="home">

    <div class="layer">
        <div class="container">
            <div class="banner-text-agile">

                <div class="row" style="background-color:#ada9a9;margin-top:-30px;">
                    <div class="col-md-3" style="margin-top:5px;">
                        <p class="imp_news" style="font-weight:bold;color:#ff0000;font-size:large">Important News</p>
                    </div>
                    <div class="col-md-9" style="margin-top:5px;">


                        <marquee id="test" behavior="scroll" direction="left" width="100%" height="25" scrolldelay="1" scrollamount="7" onmouseover="document.all.test.stop()" onmouseout="document.all.test.start()">

                            <p class="float_left strong" style="font-weight:bold;color:#0094ff;font-size:larger">
                                <a href="@Url.Action("ComingSoon","Home")">
                                    Our new project is coming on New Rajendra Nagar, Raipur with World class Eye care facility shortly. 
                                </a>
                           
                            </p>
                        </marquee>

                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="row" style="margin-top:40px;margin-left:90px;">
                    <div class="col-lg-6 p-0">
                        <!-- banner slider-->
                        <div class="csslider infinity" id="slider1">
                            <input type="radio" name="slides" checked="checked" id="slides_1" />
                            <input type="radio" name="slides" id="slides_2" />
                            <input type="radio" name="slides" id="slides_3" />
                            <ul class="banner_slide_bg">
                                <li>
                                    <div class="container-fluid">
                                        <div class="w3ls_banner_txt">
                                            <a href="@Url.Action("Index","HomeEye")">
                                                <img src="~/HospitalDemoSimple/eye-hospital.jpg" />
                                            </a>



                                            @*<center style="margin-left:-200px;"> <a href="@Url.Action("Index","HomeEye")" class="btn btn-banner1 my-sm-3 mb-3">Eye Hospital</a></center>*@
                                        </div>
                                    </div>
                                </li>


                            </ul>
                            @*<div class="navigation">
                                    <div>
                                        <label for="slides_1"></label>
                                        <label for="slides_2"></label>
                                        <label for="slides_3"></label>
                                    </div>
                                </div>*@
                        </div>
                        <!-- //banner slider-->

                    </div>
                    <div class="col-lg-6 col-md-8">
                        <ul class="banner_slide_bg">
                            <li>
                                <div class="container-fluid">
                                    <div class="w3ls_banner_txt">
                                        <a href="@Url.Action("Index","Home")">
                                            <img src="~/HospitalDemoSimple/women-hospital.jpg" />
                                        </a>
                                        @*<center style="margin-left:-100px;"> <a href="@Url.Action("Index","Home")" class="btn btn-banner1 my-sm-3 mb-3">Womens Hospital</a></center>*@
                                        @*<a href="contact.html" class="btn btn-banner1 my-sm-3 mb-3">Consult a dentist</a>*@
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>


<div class="header-top">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12">

                <ul class="d-lg-flex header-w3_pvt" style="margin-left:150px;">
                    &nbsp;&nbsp;&nbsp;
                    <li>
                        © 2019-2020 Sai Baba Hospital.
                    </li> &nbsp;&nbsp;&nbsp;&nbsp;
                    @*<li>

                        Design & Developed by -  <a href="#" target="_blank" style="color:#0094ff;font-weight:bold"> </a>
                    </li>*@

                </ul>


            </div>

        </div>
    </div>
</div>

SaiBabaHospital/Views/Home/Social.cshtml
@{
    ViewBag.Title = "Social";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<img src="~/HospitalDemoSimple/aboutbanner.jpg" />

SaiBabaHospital/Views/Home/TPA.cshtml
@{
    ViewBag.Title = "TPA";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<img src="~/HospitalDemoSimple/aboutbanner.jpg" />